version: "3"

vars:
  BUILD_PATH: "./dist/"

  PACKAGE_NAME: "vscode-theme-my-darcula"
  PACKAGE_VERSION: "1.0.0"
  PACKAGE_PATH: "{{.BUILD_PATH}}/{{.PACKAGE_NAME}}-{{.PACKAGE_VERSION}}.vsix"

  WORKSPACE_DIR: "/workspaces/{{.PACKAGE_NAME}}"

  DEV_DOCKER_IMAGE: "{{.PACKAGE_NAME}}:{{.PACKAGE_VERSION}}-dev"
  DEV_DOCKERFILE_PATH: ".devcontainer/Dockerfile.dev"

tasks:
  # ----------------------------------------------------------------------------
  # Default
  # ----------------------------------------------------------------------------
  default:
    desc: "Show all tasks"
    cmds:
      - ./bin/task --list-all

  # ----------------------------------------------------------------------------
  # Dependencies
  # ----------------------------------------------------------------------------

  "dependencies:install":
    desc: "Install dependencies"
    cmds:
      - task: "dev:dependencies:install"

  "dev:dependencies:install":
    desc: "Install dev dependencies"
    cmds:
      - yarn install
        --immutable
        {{.CLI_ARGS}}

  # ----------------------------------------------------------------------------
  # Packaging and Publishing
  # ----------------------------------------------------------------------------

  "pack":
    desc: "Package VSCode Extension"
    cmds:
      - mkdir -p {{.BUILD_PATH}}
      - yarn exec
        vsce package
        --no-dependencies
        --allow-missing-repository
        -o {{.PACKAGE_PATH}}

  "publish":
    desc: "Publish VSCode Extension"

  # ----------------------------------------------------------------------------
  # Docker
  # ----------------------------------------------------------------------------

  "dev:docker:run":
    desc: "Run docker container"
    cmds:
      - docker run -it --rm
        -v {{.ROOT_DIR}}:{{.WORKSPACE_DIR}}
        -w {{.WORKSPACE_DIR}}
        {{.DEV_DOCKER_IMAGE}}
        {{.CLI_ARGS}} || true

  "dev:docker:build":
    desc: "Build docker image"
    cmds:
      - docker buildx build
        -t {{.DEV_DOCKER_IMAGE}}
        -f {{.DEV_DOCKERFILE_PATH}}
        {{.ROOT_DIR}}
        {{.CLI_ARGS}}

  # ----------------------------------------------------------------------------
  # Lint
  # ----------------------------------------------------------------------------

  "lint":
    desc: "Run linting"
  #   deps:
  #     - task: "lint:yamllint"

  "lint:fix":
    desc: "Run linting and write to files"
    # cmds:
    #   - task: "lint:ruff:fix"
    #   - task: "lint:black:fix"

  # "lint:yamllint":
  #   desc: "Linting (yamllint)"
  #   cmds:
  #     - poetry run
  #       yamllint
  #         --config-file .yamllint.yml
  #         --strict
  #         {{.ROOT_DIR}}
  #         {{.CLI_ARGS}}
