version: '3'

vars:
  VERSION: '1.0.0'
  WORKSPACE_DIR: '/workspaces/vscode-theme-my-darcula'
  DEV_DOCKER_IMAGE: 'vscode-theme-my-darcula:{{.VERSION}}-dev'
  DEV_DOCKERFILE_PATH: '.devcontainer/Dockerfile.dev'

tasks:

  # ----------------------------------------------------------------------------
  # Default
  # ----------------------------------------------------------------------------
  default:
    desc: "Show all tasks"
    cmds:
      - ./bin/task --list-all

  # ----------------------------------------------------------------------------
  # Dependencies
  # ----------------------------------------------------------------------------

  "dependencies:install":
    desc: "Install dependencies"
    cmds:
      - task: "dev:dependencies:install"

  "dev:dependencies:install":
    desc: "Install dev dependencies"
    cmds:
      - yarn install
        --immutable
        {{.CLI_ARGS}}

  # ----------------------------------------------------------------------------
  # Packaging and Publishing
  # ----------------------------------------------------------------------------

  "pack":
    desc: "Package VSCode Extension"
    cmds:
      - yarn exec
        vsce package
        --no-yarn
        --allow-missing-repository

  "publish":
    desc: "Publish VSCode Extension"

  # ----------------------------------------------------------------------------
  # Docker
  # ----------------------------------------------------------------------------

  "dev:docker:run":
    desc: "Run docker container"
    cmds:
      - docker run -it --rm
        -v {{.ROOT_DIR}}:{{.WORKSPACE_DIR}}
        -w {{.WORKSPACE_DIR}}
        {{.DEV_DOCKER_IMAGE}}
        {{.CLI_ARGS}} || true

  "dev:docker:build":
    desc: "Build docker image"
    cmds:
      - docker buildx build
        -t {{.DEV_DOCKER_IMAGE}}
        -f {{.DEV_DOCKERFILE_PATH}}
        {{.ROOT_DIR}}
        {{.CLI_ARGS}}

  # ----------------------------------------------------------------------------
  # Lint
  # ----------------------------------------------------------------------------

  "lint":
    desc: "Run linting"
  #   deps:
  #     - task: "lint:yamllint"

  "lint:fix":
    desc: "Run linting and write to files"
    # cmds:
    #   - task: "lint:ruff:fix"
    #   - task: "lint:black:fix"

  # "lint:yamllint":
  #   desc: "Linting (yamllint)"
  #   cmds:
  #     - poetry run
  #       yamllint
  #         --config-file .yamllint.yml
  #         --strict
  #         {{.ROOT_DIR}}
  #         {{.CLI_ARGS}}
