name: CI

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    tags:
      - "CP/v[0-9]+.[0-9]+.[0-9]+"

env:
  PACKAGE_PATH: "vscode-theme-my-darcula-${{ github.ref_name }}.vsix"
  ARTIFACT_DIR: "./dist/release/"

jobs:
  build:
    runs-on: "ubuntu-22.04"
    timeout-minutes: 10

    steps:
      - name: "Checkout"
        uses: "actions/checkout@d632683dd7b4114ad314bca15554477dd762a938" # v4.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1

      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: .
          load: true
          push: false
          tags: user/app:latest

      - name: Run
        uses: tj-actions/docker-run@v2
        with:
          image: user/app:latest
          name: user-app
          args: |
            echo "Hello World"

  #     - name: "Upload a Build Artifact"
  #       uses: "actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874" #v4.4.0
  #       with:
  #         name: "vscode-theme"
  #         path: "${{ env.PACKAGE_PATH }}"

  # publish:
  #   needs: ["build"]
  #   if: startsWith(github.ref, 'refs/tags/')
  #   runs-on: "ubuntu-22.04"
  #   timeout-minutes: 10

  #   permissions:
  #     contents: write

  #   steps:
  #     - name: "Download a Build Artifact"
  #       uses: "actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16" #v4.1.8
  #       with:
  #         name: "vscode-theme"
  #         path: "${{ env.ARTIFACT_DIR }}"

  #     - name: "GH Release"
  #       uses: "softprops/action-gh-release@c062e08bd532815e2082a85e87e3ef29c3e6d191" # v2.0.8
  #       with:
  #         files: "${{ env.ARTIFACT_DIR }}${{ env.PACKAGE_PATH }}"
