name: CI

on:
  push:
    branches: ["main"]
    tags:
      - "*"
    paths-ignore:
      - "**.md"
      - "README.md"
      - "LICENSE"

  pull_request:
    branches: ["main"]
    paths-ignore:
      - "**.md"
      - "README.md"
      - "LICENSE"

  workflow_dispatch:

env:
  PACKAGE_PATH: "README.md"
  ARTIFACT_DIR: "./dist/release/"

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 #v4.4.0
        with:
          name: "vscode-theme"
          path: ${{ env.PACKAGE_PATH }}

  publish:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    permissions:
      contents: write

    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 #v4.1.8
        with:
          name: "vscode-theme"
          path: ${{ env.ARTIFACT_DIR }}

      - name: GH Release
        uses: softprops/action-gh-release@c062e08bd532815e2082a85e87e3ef29c3e6d191 # v2.0.8

        with:
          files: ${{ env.ARTIFACT_DIR }}${{ env.PACKAGE_PATH }}
