# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
    tags:
      - "*"
    paths-ignore:
      - '**.md'
      - "README.md"
      - "LICENSE"

  pull_request:
    branches: ["main"]
    paths-ignore:
      - '**.md'
      - "README.md"
      - "LICENSE"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# permissions:
# actions: read|write|none
# attestations: read|write|none
# checks: read|write|none
# contents: read|write|none
# deployments: read|write|none
# id-token: write|none
# issues: read|write|none
# discussions: read|write|none
# packages: read|write|none
# pages: read|write|none
# pull-requests: read|write|none
# repository-projects: read|write|none
# security-events: read|write|none
# statuses: read|write|none

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - name: Foo
        run: pwd && ls -la . && ./bin/task

      - name: Docker
        run: docker --version

      # - name: Release
      #   uses: softprops/action-gh-release@v2
      #   if: startsWith(github.ref, 'refs/tags/')

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 #v4.4.0
        with:
          name: "VSCode theme file"
          path: "README.md"

