name: "Changesets"

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions: {} # disable permissions

jobs:
  changesets:
    runs-on: "ubuntu-22.04"
    timeout-minutes: 10

    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - name: "Checkout Repo"
        uses: "actions/checkout@d632683dd7b4114ad314bca15554477dd762a938" # v4.2.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install Dependencies
        run: corepack enable && yarn install --immutable

      - name: "Create Release Pull Request"
        uses: changesets/action@v1
        id: changesets
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}
        with:
          createGithubReleases: true
          commit: "chore(repo): Version packages [skip ci]"
          version: yarn exec changeset version
          publish: yarn exec changeset tag

# 3
