name: "Changesets"

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions: {} # disable permissions

jobs:
  changesets:
    runs-on: "ubuntu-22.04"
    timeout-minutes: 10

    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - name: "Checkout Repo"
        uses: "actions/checkout@d632683dd7b4114ad314bca15554477dd762a938" # v4.2.0
        with:
          fetch-depth: 0
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Import GPG
        uses: crazy-max/ghaction-import-gpg@v6.1.0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: true

      - name: Foo
        run: |
          git config --list

      - name:  Bar
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          # git remote set-url origin https://x-access-token/:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository }}

      - name: Foo2
        run: |
          git config --list

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install Dependencies
        run: corepack enable && yarn install --immutable

      - name: "Create Release Pull Request"
        uses: changesets/action@v1
        id: changesets
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          createGithubReleases: false
          setupGitUser: false
          commit: "chore(repo): Version packages [skip ci]"
          version: yarn exec changeset version
          publish: yarn exec changeset tag
