name: "Checkout"

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checkout:
    runs-on: "ubuntu-22.04"
    timeout-minutes: 5

    steps:
      - uses: "${{ github.ref }}/.github/workflows/checkout.yml"
      - name: Foo
        run: "ls -la ./"

  check:
    runs-on: "ubuntu-22.04"
    timeout-minutes: 5

    steps:
      - name: Foo
        run: "ls -la ./"
