name: "Checkout"

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checkout:
    steps:
      - uses: ./.github/workflows/checkout.yml
      - name: Foo
        run: "ls -la ./"

  check:
    steps:
      - name: Foo
        run: "ls -la ./"
