name: "CI"

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: "ubuntu-22.04"
    timeout-minutes: 5

    steps:
      - name: "Checkout Repo"
        uses: "actions/checkout@d632683dd7b4114ad314bca15554477dd762a938" # v4.2.0
        with:
          repository: "${{ github.repository }}"
          ref: "${{ github.event.repository.default_branch }}"
          fetch-depth: 1

      - name: "Set up Docker Buildx"
        uses: "docker/setup-buildx-action@8026d2bc3645ea78b0d2544766a1225eb5691f89" # v3.7.0

      - name: "Build docker image"
        uses: "docker/build-push-action@v3"
        with:
          context: .
          load: true
          push: false
          tags: "builder:latest"
          cache-from: "type=gha"
          cache-to: "type=gha,mode=max"

      - name: "Packaging extension"
        uses: "addnab/docker-run-action@4f65fabd2431ebc8d299f8e5a018d79a769ae185" # v3
        with:
          image: "builder:latest"
          options: "-v ${{ github.workspace }}/dist:/workspaces/vscode-theme-my-darcula/dist"
          run: |
            sudo chown -R node:node ./dist &&
            task pack

      - name: "Upload a Build Artifact"
        uses: "actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874" #v4.4.0
        with:
          name: "vscode-theme-my-darcula-${GITHUB_SHA::7}"
          path: "./dist/**/*.vsix"
