name: "Publish"

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish:
    runs-on: "ubuntu-22.04"
    timeout-minutes: 10

    steps:
      - name: "Checkout Repo"
        uses: "actions/checkout@d632683dd7b4114ad314bca15554477dd762a938" # v4.2.0
        with:
          fetch-depth: 1
