name: "Release"

on:
  workflow_dispatch:
  push:
    tags: [ 'v*.*.*' ]

jobs:
  release:
    runs-on: "ubuntu-22.04"
    timeout-minutes: 5

    steps:
      - name: "Checkout Repo"
        uses: "actions/checkout@d632683dd7b4114ad314bca15554477dd762a938" # v4.2.0
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.event.repository.default_branch }}
          fetch-depth: 1

      - name: "Release"
        run: "ls -la ../"
