name: "Release"

on:
  workflow_dispatch:
  push:
    tags: ["v*.*.*"]

permissions:
  contents: write

jobs:
  release:
    runs-on: "ubuntu-22.04"
    timeout-minutes: 10

    steps:
      - name: "Checkout Repo"
        uses: "actions/checkout@d632683dd7b4114ad314bca15554477dd762a938" # v4.2.0
        with:
          fetch-depth: 0

      - name: "Get Git tag"
        id: git-tag
        run: |
          echo "GITHUB_TAG_LAST=$(git tag --sort=committerdate | grep -E '[0-9]' | tail -1 | cut -b 2-7)" >> "$GITHUB_OUTPUT"

      - name: "Get package version"
        id: package-version
        run: |
          echo "PACKAGE_VERSION=$(grep -o '"version": "[^"]*"' package.json | sed 's/"version": "\(.*\)"/\1/')" >> "$GITHUB_OUTPUT"

      - name: "Version check"
        if: ${{ steps.git-tag.outputs.GITHUB_TAG_LAST != steps.package-version.outputs.PACKAGE_VERSION }}
        run: |
          echo 'GITHUB_TAG_LAST: ${{ steps.git-tag.outputs.GITHUB_TAG_LAST }}'
          echo 'PACKAGE_VERSION: ${{ steps.package-version.outputs.PACKAGE_VERSION }}'
          exit 1

      - name: "Set up Docker Buildx"
        uses: "docker/setup-buildx-action@8026d2bc3645ea78b0d2544766a1225eb5691f89" # v3.7.0

      - name: "Build Docker images"
        uses: "docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75" # v6.9.0
        env:
          DOCKER_BUILD_SUMMARY: false
        with:
          context: .
          load: true
          push: false
          tags: "build-env:latest"
          cache-from: "type=gha"
          cache-to: "type=gha,mode=max"

      - name: "Packaging extension"
        uses: "addnab/docker-run-action@4f65fabd2431ebc8d299f8e5a018d79a769ae185" # v3
        with:
          image: "build-env:latest"
          options: "-v ${{ github.workspace }}/dist:/workspaces/vscode-theme-my-darcula/dist"
          run: |
            sudo chown -R node:node ./dist &&
            task pack

      - name: "Upload a Build Artifact"
        uses: "actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874" #v4.4.0
        with:
          name: "vscode-theme-my-darcula_v${{ steps.git-tag.outputs.GITHUB_TAG_LAST }}"
          path: "./dist/**/*.vsix"

      - name: "Release"
        uses: "softprops/action-gh-release@c062e08bd532815e2082a85e87e3ef29c3e6d191" # v2.0.8
        with:
          files: "./dist/**/*.vsix"
