name: "Release"

on:
  workflow_dispatch:
  push:
    tags: ["v*.*.*"]

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"

permissions: {} # disable permissions

jobs:
  release:
    if: github.repository == "sjlex/vscode-theme-my-darcula"
    runs-on: "ubuntu-22.04"
    timeout-minutes: 10

    permissions:
      contents: write

    env:
      PACKAGE_NAME: "vscode-theme-my-darcula"
      DIST_DIR: "dist"

    steps:
      - name: "Checkout Repo"
        uses: "actions/checkout@d632683dd7b4114ad314bca15554477dd762a938" # v4.2.0
        with:
          fetch-depth: 0

      - name: "Get the latest version tag"
        id: git-tag-latest
        run: |
          echo "GITHUB_TAG_LATEST=$(git tag --sort=committerdate | grep -E '[0-9]' | tail -1 | cut -b 2-7)" >> "$GITHUB_ENV"

      - name: "Get package version"
        id: package-version
        run: |
          echo "PACKAGE_VERSION=$(grep -o '"version": "[^"]*"' package.json | sed 's/"version": "\(.*\)"/\1/')" >> "$GITHUB_ENV"

      - name: "Version check"
        if: ${{ env.GITHUB_TAG_LATEST != env.PACKAGE_VERSION }}
        run: |
          echo 'GITHUB_TAG_LATEST: ${{ env.GITHUB_TAG_LATEST }}'
          echo 'PACKAGE_VERSION: ${{ env.PACKAGE_VERSION }}'
          exit 1

      - name: "Set up Docker Buildx"
        uses: "docker/setup-buildx-action@8026d2bc3645ea78b0d2544766a1225eb5691f89" # v3.7.0

      - name: "Build Docker images"
        uses: "docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75" # v6.9.0
        env:
          DOCKER_BUILD_SUMMARY: false
        with:
          context: .
          load: true
          push: false
          tags: "builder:latest"
          cache-from: "type=gha"
          cache-to: "type=gha,mode=max"

      - name: "Packaging extension"
        uses: "addnab/docker-run-action@4f65fabd2431ebc8d299f8e5a018d79a769ae185" # v3
        env:
          MOUNT_DIR: "${{ github.workspace }}/${{ env.DIST_DIR }}"
          MOUNT_TARGET_DIR: "/workspaces/${{ env.PACKAGE_NAME }}/${{ env.DIST_DIR }}"
        with:
          image: "builder:latest"
          options: "-v ${{ env.MOUNT_DIR }}:${{ env.MOUNT_TARGET_DIR }}"
          run: |
            sudo chown -R node:node ${{ env.MOUNT_TARGET_DIR }} &&
            task pack

      - name: "Upload a Build Artifact"
        uses: "actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874" #v4.4.0
        env:
          ARTIFACT_NAME: "${{ env.PACKAGE_NAME }}_v${{ env.GITHUB_TAG_LATEST }}"
          ARTIFACT_PATH: "./${{ env.DIST_DIR }}/**/*.vsix"
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT_PATH }}

      - name: "Release"
        uses: "softprops/action-gh-release@c062e08bd532815e2082a85e87e3ef29c3e6d191" # v2.0.8
        env:
          ARTIFACT_PATH: "./${{ env.DIST_DIR }}/**/*.vsix"
        with:
          files: ${{ env.ARTIFACT_PATH }}

      # TODO
      - name: "Publish"
        uses: "addnab/docker-run-action@4f65fabd2431ebc8d299f8e5a018d79a769ae185" # v3
        with:
          image: "builder:latest"
          run: |
            # task publish -p ${{ secrets.DEV_AZURE_PAT }}
